implement swapDebt function
DeltaPrimeLabs/deltaprime-primeloans pull request #159
Opened 2023-03-02 15:07 UTC by 0xlock

2023-03-03 10:46 UTC, mbare0 commented on contracts/facets/AssetsOperationsFacet.sol
> +            borrowAmount = _repayAmount * prices[0] * 101 / prices[1] / 100;
101 and 100 is to account for slippage?

2023-03-03 10:48 UTC, mbare0 commented on contracts/facets/AssetsOperationsFacet.sol
> +        if (fromToken.balanceOf(address(this)) > 0) {
are you sure it's correct? if `fromToken.balanceOf(address(this)` -> DiamondStorageLib.removeOwnedAsset(_fromAsset)

if `toToken.balanceOf(address(this)` -> DiamondStorageLib.addOwnedAsset(_toAsset)

2023-03-05 17:02 UTC, kavsky02 commented on contracts/facets/AssetsOperationsFacet.sol
> +            borrowAmount = _repayAmount * prices[0] * 101 / prices[1] / 100;
@0xlock

2023-03-05 17:06 UTC, kavsky02 commented on contracts/facets/AssetsOperationsFacet.sol
> +        _repayAmount = Math.min(_repayAmount, fromToken.balanceOf(address(this)) - beforeBalance);
shouldn't it be just `fromToken.balanceOf()` without subtracting the `beforeBalance`? 
Just to cover a scenario where we didn't get enough output from the swap but maybe the user already had some `fromToken` balance before?

2023-03-05 17:09 UTC, kavsky02 commented on contracts/facets/AssetsOperationsFacet.sol
> +        if (fromToken.balanceOf(address(this)) > 0) {
Yeah, given that we can have some dust leftovers both from `fromToken` and `toToken` maybe it best to check both of the balances for being > 0 and then add/remove appropriately?

2023-03-05 17:11 UTC, kavsky02 requested changes

2023-03-05 17:11 UTC, kavsky02 commented on test/integration/smart-loan/smart-loan-swap-debt.test.ts
> +            expect(fromWei(await wrappedLoan.getDebt())).to.be.closeTo(400, 0.02);
Could you also add `expect` statements for the debt token denomination?  So to call pool contracts themselves before and after debtswap and check `getBorrowed()` for the loan address to ensure that the debt exposure did change indeed?

2023-03-06 01:00 UTC, 0xlock commented on contracts/facets/AssetsOperationsFacet.sol
> +            borrowAmount = _repayAmount * prices[0] * 101 / prices[1] / 100;
yes correct! @mbare0 @kavsky02

2023-03-06 01:06 UTC, 0xlock commented on contracts/facets/AssetsOperationsFacet.sol
> +        if (fromToken.balanceOf(address(this)) > 0) {
no need to check balance of toToken
because we swap the entire toToken borrowed and there will be no diff between the prev toToken balance and new toToken balance

2023-03-06 01:07 UTC, 0xlock commented on contracts/facets/AssetsOperationsFacet.sol
> +        _repayAmount = Math.min(_repayAmount, fromToken.balanceOf(address(this)) - beforeBalance);
yeah, it makes sense to me.
will update it

2023-03-06 01:08 UTC, 0xlock commented on test/integration/smart-loan/smart-loan-swap-debt.test.ts
> +            expect(fromWei(await wrappedLoan.getDebt())).to.be.closeTo(400, 0.02);
okay, I'll work on it

2023-03-06 15:51 UTC, kavsky02 commented on contracts/facets/avalanche/PangolinDEXFacet.sol
> +        return 0x82BBAA3B0982D88741B275aE1752DB85CAfe3c65;
Don't commit changes to this file, please

2023-03-06 15:51 UTC, kavsky02 commented on contracts/facets/avalanche/TraderJoeDEXFacet.sol
> +        return 0xa4d0806d597146df93796A38435ABB2a3cb96677;
Don't commit changes to this file, please

2023-03-06 15:52 UTC, kavsky02 commented on contracts/lib/local/DeploymentConstants.sol
> -    address private constant _DIAMOND_BEACON_ADDRESS = 0x02df3a3F960393F5B349E40A599FEda91a7cc1A7;
Don't commit changes to this file, please

2023-03-07 09:38 UTC, 0xlock commented on contracts/facets/avalanche/PangolinDEXFacet.sol
> +        return 0x82BBAA3B0982D88741B275aE1752DB85CAfe3c65;
removed!

2023-03-07 09:39 UTC, 0xlock commented on contracts/facets/avalanche/TraderJoeDEXFacet.sol
> +        return 0xa4d0806d597146df93796A38435ABB2a3cb96677;
removed!

2023-03-07 12:26 UTC, merged

2023-03-24 15:45 UTC, mbare0 commented on contracts/facets/AssetsOperationsFacet.sol
> +                amountOut: 0,
I think slippage protection is needed here. We can provide it from the FE.

2023-03-24 15:45 UTC, mbare0 commented on contracts/facets/AssetsOperationsFacet.sol
> +        emit Borrowed(msg.sender, _toAsset, borrowAmount, block.timestamp);
we could do a `DebtSwap` event for the UI

2023-03-24 15:46 UTC, mbare0 commented on contracts/facets/AssetsOperationsFacet.sol
> +        emit Borrowed(msg.sender, _toAsset, borrowAmount, block.timestamp);
would keep them as well tho

2023-03-24 15:46 UTC, mbare0 commented on contracts/facets/AssetsOperationsFacet.sol
> +                borrowAmount = _repayAmount * prices[0] * 101 / prices[1] / 100;
101/100 is to account for debt compounding or what?

2023-03-24 15:51 UTC, mbare0 commented on contracts/facets/AssetsOperationsFacet.sol
> +            DiamondStorageLib.addOwnedAsset(_fromAsset, address(fromToken));
it's to account for left overs from a swap?

2023-03-24 15:52 UTC, mbare0 commented on contracts/facets/AssetsOperationsFacet.sol
> +    function swapDebt(bytes32 _fromAsset, bytes32 _toAsset, uint256 _repayAmount, address[] calldata _path, address[] calldata _adapters) external onlyOwner remainsSolvent {
would be good to have `_borrowAmount` or sth like that to control slippage

2023-03-24 15:57 UTC, jakub-wojciechowski commented on contracts/facets/AssetsOperationsFacet.sol
> +                borrowAmount = _repayAmount * prices[0] * 101 / prices[1] / 100;
??? (Looks strange)

2023-03-24 16:02 UTC, jakub-wojciechowski commented on contracts/facets/AssetsOperationsFacet.sol
> +                amountOut: 0,
Hmmm, it looks like we want to repay a certain amount, wouldn't it be better to put out as a parameter

2023-03-24 16:07 UTC, jakub-wojciechowski commented on contracts/facets/AssetsOperationsFacet.sol
> +            DiamondStorageLib.addOwnedAsset(_fromAsset, address(fromToken));
I think we should also do it for the toToken

2023-03-24 16:21 UTC, mbare0 commented on contracts/facets/AssetsOperationsFacet.sol
> +        fromAssetPool.repay(_repayAmount);
shouldn't we update "protocol exposure" as well?

2023-03-25 13:19 UTC, kavsky02 commented on contracts/facets/AssetsOperationsFacet.sol
> +                borrowAmount = _repayAmount * prices[0] * 101 / prices[1] / 100;
@0xlock I think it was here indeed to account for the slippage, right? @jakub-wojciechowski what would you say is a good way to do that?

2023-03-25 13:21 UTC, kavsky02 commented on contracts/facets/AssetsOperationsFacet.sol
> +                amountOut: 0,
@mbare0 I think the slippage protection is a good idea.

2023-03-25 13:22 UTC, kavsky02 commented on contracts/facets/AssetsOperationsFacet.sol
> +                amountOut: 0,
@jakub-wojciechowski afaik this router does not expose a method for calculating the amountIn to get a specific amountOut. It only works the other way around unfortunately

2023-03-25 13:26 UTC, kavsky02 commented on contracts/facets/AssetsOperationsFacet.sol
> +                amountOut: 0,
Actually this may be the best approach. Because you're right that the end goal here is to repay a certain amount. And if we use `repayAmount` as the `minimumOut` and we add one extra parameter to this method `borrowAmount` instead of calculating it then it those two together can be used to control the slippage.

2023-03-25 13:27 UTC, kavsky02 commented on contracts/facets/AssetsOperationsFacet.sol
> +        fromAssetPool.repay(_repayAmount);
We don't update protocol exposure in borrow/repay as we don't count it as protocol exposure as it's coming from our lending pools. We change exposure on fund/withdraw/swap/stake etc.

2023-03-25 13:29 UTC, kavsky02 commented on contracts/facets/AssetsOperationsFacet.sol
> +            DiamondStorageLib.addOwnedAsset(_fromAsset, address(fromToken));
As @0xlock explained in the resolved conversation above the whole balance of `toToken` gets swapped to `fromToken` so there will be no outstanding balance of that asset hence no need to add this owned asset.

2023-03-25 13:30 UTC, kavsky02 commented on contracts/facets/AssetsOperationsFacet.sol
> +    function swapDebt(bytes32 _fromAsset, bytes32 _toAsset, uint256 _repayAmount, address[] calldata _path, address[] calldata _adapters) external onlyOwner remainsSolvent {
yes, I think that's the best approach as we don't have to rely on this 101/100 slippage hardcoding

2023-03-26 11:47 UTC, kavsky02 commented on contracts/facets/AssetsOperationsFacet.sol
> +        emit Borrowed(msg.sender, _toAsset, borrowAmount, block.timestamp);
Done ✅