Vesting Distributor
DeltaPrimeLabs/deltaprime-primeloans pull request #172
Opened 2023-03-22 12:47 UTC by mbare0

2023-03-22 12:58 UTC, 0xlock requested changes
I've added some comments to `VestingDistributor` contract

2023-03-22 12:58 UTC, 0xlock commented on contracts/VestingDistributor.sol
> +        if (unlockTimestamp[account] == 0 || unlockTimestamp[account] < block.timestamp) revert UserLocked();
I think this can be `if (unlockTimestamp[account] == 0) revert UserLocked();`
wdyt?

2023-03-22 12:58 UTC, 0xlock commented on contracts/VestingDistributor.sol
> +        uint256 timeFromUnlock = block.timestamp - unlockTimestamp[account];
We can add below after this line to make sure `timeFromUnlock` is always less than `unvestingTime[account`
`if (timeFromUnlock > unvestingTime[account]) timeFromUnlock = unvestingTime[account];`

2023-03-22 12:58 UTC, 0xlock commented on contracts/VestingDistributor.sol
> +        if (block.timestamp < lastUpdated + updateInterval) revert DistributeTooEarly();
We need to update `lastUpdated` after this if statement.
`lastUpdated = block.timestamp;`

2023-03-22 12:58 UTC, 0xlock commented on contracts/VestingDistributor.sol
> +            if (unlockTimestamp[participants[i]] > 0 && block.timestamp > unvestingTime[participants[i]]) {
Instead of `block.timestamp > unvestingTime[participants[i]]`, it should be like this
`(block.timestamp - unlockTimestamp[participants[i]]) > unvestingTime[participants[i]]`

2023-03-22 12:58 UTC, 0xlock commented on contracts/VestingDistributor.sol
> +       withdrawn[msg.sender] -= amount;
We should use `+=` instead of `-=`, right?

2023-03-22 12:58 UTC, 0xlock commented on contracts/VestingDistributor.sol
> +    function startVesting(uint256 amount, uint256 time) public {
Missing validation for `time` param.

2023-03-22 12:58 UTC, 0xlock commented on contracts/VestingDistributor.sol
> +    function getMultiplier(uint256 time) public returns (uint256){
This should be further updated to be consistent with proposal.

2023-03-22 13:05 UTC, 0xlock commented on contracts/VestingDistributor.sol
> +                delete participants[i];
I think we should pop participant from array instead of resetting the value to address(0)

2023-03-22 13:51 UTC, mbare0 commented on contracts/VestingDistributor.sol
> +        if (block.timestamp < lastUpdated + updateInterval) revert DistributeTooEarly();
yes

2023-03-22 13:51 UTC, mbare0 commented on contracts/VestingDistributor.sol
> +       withdrawn[msg.sender] -= amount;
exactly

2023-03-22 13:52 UTC, mbare0 commented on contracts/VestingDistributor.sol
> +                delete participants[i];
right, that was just a shortcut

2023-03-22 13:55 UTC, mbare0 commented on contracts/VestingDistributor.sol
> +    function getMultiplier(uint256 time) public returns (uint256){
what do you mean? to cover more options (for 1, 2,3... days)? then right

2023-03-22 13:58 UTC, 0xlock commented on contracts/VestingDistributor.sol
> +    function getMultiplier(uint256 time) public returns (uint256){
yeah, I meant that

2023-03-24 15:07 UTC, kavsky02 commented on contracts/VestingDistributor.sol
> +        if (time > 2_592_000) revert InvalidVestingTime();
can we replace `2_592_000` with a `CONSTANT` and add a comment to the constant definition that will explain where does that value come from? e.g `CONSANT_FOO = 123_456_789; // 60 seconds * 24 hours * 7 days`

2023-03-24 15:14 UTC, kavsky02 commented on contracts/VestingDistributor.sol
> +        if (time > 2_592_000) return 1.5e18; // min. 30 days
That's not consistent with the L53 requirement `if (time > 2_592_000) revert InvalidVestingTime();`
Let's come up with a concrete list of different vesting tiers and apply it

2023-03-24 15:20 UTC, kavsky02 commented on contracts/VestingDistributor.sol
> +        // lastUpdated = block.timestamp;
uncomment?

2023-03-24 15:26 UTC, kavsky02 commented on contracts/VestingDistributor.sol
> +            rewardAmount[lastUpdated] = pool.balanceOf(address(this));
Where in `Pool.sol` or in this contract code is the change that assigns any `balance` to this (`address(this)`) contract?

2023-03-24 15:33 UTC, kavsky02 commented on contracts/VestingDistributor.sol
> +            uint256 participantReward = rewards * (locked[participant] - withdrawn[msg.sender]) * multiplier[participant] / 1e18 / totalLockedMultiplied;
in this case only `keeper` can execute this method so he'll be the `msg.sender` but the only way to change `withdrawn[]` value seems to be the `updateWithdrawn` method that can only be called by the `Pool` and then `msg.sender` is equal to `Pool`.
Is it a desired behaviour?

2023-03-24 15:36 UTC, kavsky02 commented on contracts/VestingDistributor.sol
> +        if (time > 2_592_000) return 1.5e18; // min. 30 days
![image](https://user-images.githubusercontent.com/95619352/227571646-3cfae8df-7d7f-4359-9931-738996c882e6.png)
Let's use this formula but for gas savings hardcode values for 1-30 days accordingly to the formula

2023-03-24 16:04 UTC, mbare0 commented on contracts/VestingDistributor.sol
> +            uint256 participantReward = rewards * (locked[participant] - withdrawn[msg.sender]) * multiplier[participant] / 1e18 / totalLockedMultiplied;
yeah it should be `withdrawn[participant])` here (@0xlock please confirm)

2023-03-24 16:13 UTC, 0xlock commented on contracts/VestingDistributor.sol
> +            uint256 participantReward = rewards * (locked[participant] - withdrawn[msg.sender]) * multiplier[participant] / 1e18 / totalLockedMultiplied;
@mbare0  yes, it should be `withdrawn[participant])` and we also need to update `updateWithdrawn` function to accept account parameter.

2023-03-27 16:05 UTC, 0xlock commented on contracts/VestingDistributor.sol
> +            rewardAmount[lastUpdated] = pool.balanceOf(address(this));
@kavsky02 @mbare0 do I need to fix anything regarding this?

2023-04-06 12:13 UTC, jakub-wojciechowski commented on contracts/VestingDistributor.sol
> +        if (time > 2_592_000) revert InvalidVestingTime();
We get some nasty behaviour (div by zero) with time == 0, let's validate it

2023-04-06 12:15 UTC, jakub-wojciechowski commented on contracts/VestingDistributor.sol
> +        uint256 initialUnlock = 86400 * locked[account] / unvestingTime[account]; // 1D / vesting days * locked amount
What if unvesting time is less than 1 day?

2023-04-06 12:25 UTC, jakub-wojciechowski commented on contracts/VestingDistributor.sol
> +        if (unlockTimestamp[account] == 0) revert UserLocked();
I cannot find a place where unlockTimestamp[account] is set to zero, how can I start another locking
(Shouldn't it be in the vesting contract)?

2023-04-06 13:37 UTC, jakub-wojciechowski commented on contracts/VestingDistributor.sol
> +            uint256 participantReward = rewards * (locked[participant] - withdrawn[msg.sender]) * multiplier[participant] / 1e18 / totalLockedMultiplied;
withdrawn, could be possibly greater than locked

2023-04-06 13:45 UTC, jakub-wojciechowski commented on contracts/VestingDistributor.sol
> +                locked[participant] = 0;
It looks like we need to do sth with unlock to clean the condition,
Otherwise, we start another vesting with already unlocked position

2023-04-06 13:46 UTC, jakub-wojciechowski commented on contracts/VestingDistributor.sol
> +        if (time > 2_592_000) revert InvalidVestingTime();
We should also allow locking to more than 1 day only
Otherwise we'll pay out initially more than was locked

2023-04-07 12:25 UTC, mbare0 commented on contracts/VestingDistributor.sol
> +    address keeper;
We should have an option to update the `keeper`

2023-04-07 12:36 UTC, mbare0 commented on contracts/VestingDistributor.sol
> +        if (unlockTimestamp[account] == 0) revert UserLocked();
that should be done in a keeper when it updates participants @0xlock

2023-04-07 12:41 UTC, mbare0 commented on contracts/VestingDistributor.sol
> +        uint256 initialUnlock = 86400 * locked[account] / unvestingTime[account]; // 1D / vesting days * locked amount
vesting should be always higher than 1 day @0xlock

2023-04-07 12:56 UTC, mbare0 commented on contracts/VestingDistributor.sol
> +            rewardAmount[lastUpdated] = pool.balanceOf(address(this));
I dont think so. @kavsky02 please confirm that it's ok - the test covers that

2023-04-07 13:00 UTC, mbare0 commented on contracts/VestingDistributor.sol
> +        withdrawn[msg.sender] += amount;
we should update `totalLockedMultiplied` as well

2023-04-07 13:04 UTC, mbare0 commented on contracts/VestingDistributor.sol
> +            uint256 participantReward = rewards * (locked[participant] - withdrawn[msg.sender]) * multiplier[participant] / 1e18 / totalLockedMultiplied;
@0xlock can we cover these distributed rewards in a test? Just to see if values make sense

2023-04-07 13:14 UTC, mbare0 commented on contracts/VestingDistributor.sol
> +                totalLockedMultiplied -= locked[participant] * multiplier[participant] / 1e18;
that must be checked against https://github.com/DeltaPrimeLabs/deltaprime-primeloans/pull/172/files#r1160685530

2023-04-09 14:34 UTC, kavsky02 commented on contracts/VestingDistributor.sol
> +            rewardAmount[lastUpdated] = pool.balanceOf(address(this));
Looks good to me 👍

2023-04-10 02:03 UTC, 0xlock commented on contracts/VestingDistributor.sol
> +            uint256 participantReward = rewards * (locked[participant] - withdrawn[msg.sender]) * multiplier[participant] / 1e18 / totalLockedMultiplied;
I've added a check to updateWithdrawn function to ensure withdrawn[account] is always less than locked[account]

2023-04-10 02:11 UTC, 0xlock commented on contracts/VestingDistributor.sol
> +                locked[participant] = 0;
@jakub-wojciechowski I can't understand what this means

2023-04-10 09:18 UTC, mbare0 commented on contracts/VestingDistributor.sol
> +        uint256 initialUnlock = ONE_DAY * locked[account] / unvestingTime[account]; // 1D / vesting days * locked amount
ok, actually that won't work for ONE_DAY lock- since the initialUnlock will be the full unlock

2023-04-10 10:23 UTC, 0xlock commented on contracts/VestingDistributor.sol
> +        uint256 initialUnlock = ONE_DAY * locked[account] / unvestingTime[account]; // 1D / vesting days * locked amount
@mbare0 can you please be more specific?
any recommendations for fix?

2023-04-10 10:34 UTC, mbare0 commented on contracts/VestingDistributor.sol
> +                locked[participant] = 0;
I think it means including `unlockTimestamp[participant] = 0;`, corrected

2023-04-10 10:39 UTC, merged