Feature/balancer v2
DeltaPrimeLabs/deltaprime-primeloans pull request #226
Opened 2023-08-18 14:45 UTC by mbare0

2023-08-21 00:53 UTC, 0xlock commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +        (address pool,) = vault.getPool(request.poolId);
@mbare0 would be good to add zero address check here for the `pool`

2023-08-21 00:53 UTC, 0xlock commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +        for (uint256 i; i < request.stakedTokens.length; i++) {
@mbare0 we can save `request.stakedTokens.length` to memory variable to save gas here.

2023-08-21 00:58 UTC, 0xlock commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +        for (uint256 i; i < request.stakedTokens.length; ++i) {
@mbare0 same here (gas optimization)

2023-08-21 00:58 UTC, 0xlock commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +        for (uint256 i; i < request.stakedAmounts.length; ++i ) {
@mbare0 same here

2023-08-21 00:59 UTC, 0xlock commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +            for (uint256 i; i < tokens.length - 1; i++) {
@mbare0 gas optimization

2023-08-21 01:01 UTC, 0xlock commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +        gauge.deposit(IERC20(pool).balanceOf(address(this)));
@mbare0 no need to call `IERC20(pool).balanceOf(address(this))` twice here.
we can store it to variable and use in the second place.

2023-08-21 01:04 UTC, 0xlock commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +        for (uint256 i; i < request.stakedTokens.length; ++i ) {
@mbare0 store the `request.stakedTokens.length` for gas optimization.

2023-08-21 01:10 UTC, 0xlock requested changes
Overall looks good.
Left some comments for gas optimization.

2023-08-21 09:47 UTC, kavsky02 commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +    address private constant VAULT_ADDRESS = 0xBA12222222228d8Ba445958a75a0704d566BF2C8;
Can we add something like `MASTER_` prefix for this one so that it's clear that it is some kind of main/singular vault used for all `stake/unstake` operations?

2023-08-21 09:51 UTC, kavsky02 commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +import "../../interfaces/balancer-v2/IBalancerV2Vault.sol";
Double import?

2023-08-21 09:52 UTC, kavsky02 commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +        IVault vault = IVault(VAULT_ADDRESS);
Where is it defined / imported from?

2023-08-21 10:00 UTC, kavsky02 commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +            if (request.stakedTokens[i] == address(pool) || request.stakedTokens[i] == address(gauge)) revert DepositingWrongToken();
Probably this check in obsolete given that we'll never whitelist `gauge` or `pool` as an active token.

2023-08-21 10:01 UTC, kavsky02 commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +            if (tokenManager.isTokenAssetActive(request.stakedTokens[i]) && request.stakedAmounts[i] > 0) {
First part of the check can be removed as it's already checked for all array of `stakedTokens[]` if the `stakeAmount[]` is >0.

2023-08-21 10:09 UTC, kavsky02 commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +                abi.encode(1, request.stakedAmounts, request.minBptAmount),
<img width="923" alt="image" src="https://github.com/DeltaPrimeLabs/deltaprime-primeloans/assets/95619352/3a73584c-e68e-4bf6-bff8-b746c5ec77dc">
Will this work if it is only meant to be used once during `"seeding"` the pool?

2023-08-21 10:12 UTC, mbare0 commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +        IVault vault = IVault(VAULT_ADDRESS);
The file is named `IBalancerV2Vault` and it has the `IVault` interface. Reasoning: IVault is a so general name that I didn't want to use it as a file name. On the other hand I wanted to keep the same name of interface as in the Balancer code. Open for suggestions

2023-08-21 10:14 UTC, mbare0 commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +                abi.encode(1, request.stakedAmounts, request.minBptAmount),
Indexing of enums in Solidity starts with 0 (https://ethereum.stackexchange.com/questions/21775/what-is-the-zero-value-for-an-enum), so we use the second joing `Exact Tokens Join`

2023-08-21 10:17 UTC, mbare0 commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +            if (tokenManager.isTokenAssetActive(request.stakedTokens[i]) && request.stakedAmounts[i] > 0) {
right!

2023-08-21 10:24 UTC, kavsky02 commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +        if (request.unstakedToken == address(pool) || request.unstakedToken == address(gauge)) revert UnstakingWrongToken();
We'll never whitelist `gauge` or `pool` as an active asset so probably this check is obsolete because of the one above.

2023-08-21 10:32 UTC, kavsky02 commented on contracts/facets/avalanche/BalancerV2Facet.sol
> +        //joins the pools
exit the pools

2023-08-21 10:34 UTC, kavsky02 commented on contracts/interfaces/balancer-v2/IBalancerV2Gauge.sol
> +    function claim_rewards() external;
Not used

2023-08-21 11:01 UTC, kavsky02 requested changes
Left some comments. Overall looks good! 
Should be ready once the #TODOs from the test case are resolved

2023-08-21 11:44 UTC, mbare0 commented on contracts/interfaces/balancer-v2/IBalancerV2Gauge.sol
> +    function claim_rewards() external;
Good catch! Added a method to claim Balancer rewards in the latest commit

2023-11-17 10:47 UTC, kavsky02 commented
Closing as there is a newer version of this 
https://github.com/DeltaPrimeLabs/deltaprime-primeloans/pull/228

2023-11-17 10:47 UTC, closed without merging