Dev/gmx v2
DeltaPrimeLabs/deltaprime-primeloans pull request #244
Opened 2023-11-02 11:33 UTC by kavsky02

2023-11-06 13:31 UTC, mbare0 commented on contracts/facets/AssetsOperationsFacet.sol
> +    function unfreezeAccount() external onlyWhitelistedLiquidators {
`liquidators`? not keepers?

2023-11-06 13:31 UTC, mbare0 commented on contracts/facets/AssetsExposureController.sol
> +    function resetPrimeAccountExposureForChosenAssets(bytes32[] memory assetsNames) external {
access should be limited

2023-11-06 13:31 UTC, mbare0 commented on contracts/facets/AssetsExposureController.sol
>      function resetPrimeAccountAssetsExposure() external {
similar (and we need to check for other methods as well)

2023-11-06 13:34 UTC, mbare0 commented on contracts/facets/GmxV2Facet.sol
> +        if(IERC20Metadata(deposit.addresses.market).balanceOf(address(this)) > 0){
Is there any staking mechanism in GM tokens that requires giving ownership to some GMX contract?

2023-11-06 14:59 UTC, mbare0 commented on contracts/facets/GmxV2Facet.sol
> +        resetExposureAssets[1] = tokenManager.tokenAddressToSymbol(marketToShortToken(gmToken));
`[2]`?

2023-11-13 16:40 UTC, 0xlock requested changes

2023-11-14 12:40 UTC, 0xlock requested changes

2023-11-14 12:40 UTC, 0xlock commented on contracts/interfaces/facets/arbitrum/IGmxV2ArbitrumFacet.sol
> +    function depositEthUsdcGmxV2(bool isLongToken, uint256 tokenAmount, uint256 minGmAmount, uint256 executionFee) external payable;
@kavsky02 why do we have only one deposit/withdraw function here?

2023-11-17 09:52 UTC, kavsky02 commented on contracts/interfaces/facets/arbitrum/IGmxV2ArbitrumFacet.sol
> +    function depositEthUsdcGmxV2(bool isLongToken, uint256 tokenAmount, uint256 minGmAmount, uint256 executionFee) external payable;
Size limitation of SC. But in current impl. we should be able to fit in more. Anyway, for internal testing 2 pools are enough for now.

2023-11-20 09:53 UTC, mbare0 commented on contracts/facets/AssetsExposureController.sol
>      function resetPrimeAccountAssetsExposure() external {
Pplease check if only PAs can call this method? decreaseProtocolExposure uses onlyPrimeAccountOrOwner

2023-11-20 09:54 UTC, mbare0 commented on contracts/facets/GmxV2Facet.sol
> +    function isCallerAuthorized(address _caller) internal view returns (bool){
Please check the roles and limit just to necessary keepers

2023-11-20 09:54 UTC, mbare0 commented on contracts/facets/GmxV2Facet.sol
> +                callbackGasLimit: 200000 //callbackGasLimit
is it an optimal value?

2023-11-20 09:55 UTC, mbare0 commented on contracts/facets/GmxV2Facet.sol
> +            bytes32[] memory dataFeedIds = new bytes32[](1);
important: please check if solvency (TWV) of an account changes after a GM deposit

2023-11-20 09:55 UTC, mbare0 commented on contracts/facets/GmxV2Facet.sol
> +            require((_getThresholdWeightedValuePayable() + receivedTokensWeightedUsdValue) > _getDebtPayable(), "The action may cause the account to become insolvent");
@c-gma does payable have any influence here?

2023-11-20 09:57 UTC, mbare0 commented on contracts/OnlyOwnerOrInsolvent.sol
> +            require(!_isSolvent(), "Account is solvent");
payable not required?

2023-11-20 09:58 UTC, mbare0 commented on contracts/facets/avalanche/GmxV2FacetAvalanche.sol
> +//    function depositSolUsdcGmxV2(bool isLongToken, uint256 tokenAmount, uint256 minGmAmount, uint256 executionFee) external payable onlyWhitelistedAccounts {
please restore these methods

2023-11-21 06:34 UTC, mbare0 commented on contracts/facets/GmxV2Facet.sol
> +        }
please add an Event

2023-11-21 06:35 UTC, mbare0 commented on contracts/facets/GmxV2Facet.sol
> +        }
event

2023-11-21 06:35 UTC, mbare0 commented on contracts/facets/GmxV2Facet.sol
> +        DiamondStorageLib.unfreezeAccount(msg.sender);
event here and for the other ones

2023-11-21 12:05 UTC, mbare0 commented on contracts/facets/GmxV2Facet.sol
> +    function _deposit(address gmToken, address depositedToken, uint256 tokenAmount, uint256 minGmAmount, uint256 executionFee) internal nonReentrant noBorrowInTheSameBlock onlyOwner {
please add logic that will check if `tokenAmount` is higher than balance, and uses the balance in such a case

2023-11-21 12:05 UTC, mbare0 commented on contracts/facets/GmxV2Facet.sol
> +    function _withdraw(address gmToken, uint256 gmAmount, uint256 minLongTokenAmount, uint256 minShortTokenAmount, uint256 executionFee) internal nonReentrant noBorrowInTheSameBlock onlyOwnerNoStaySo
please add logic that will check if `gmToken` is higher than GM balance, and uses the balance in such a case

2023-11-21 16:12 UTC, kavsky02 commented on contracts/facets/AssetsExposureController.sol
>      function resetPrimeAccountAssetsExposure() external {
Already investigated and will be handled as a separate upgrade

2023-11-21 16:13 UTC, kavsky02 commented on contracts/facets/GmxV2Facet.sol
> +                callbackGasLimit: 200000 //callbackGasLimit
Seems to be working just fine for now and is on the safe side of things. We can test it more in the near future to see if it can be safely decreased.

2023-11-21 16:21 UTC, kavsky02 commented on contracts/OnlyOwnerOrInsolvent.sol
> +            require(!_isSolvent(), "Account is solvent");
It is, great catch!

2023-11-21 16:23 UTC, kavsky02 commented on contracts/facets/GmxV2Facet.sol
> +        }
Okay! We don't have events for removing/adding owned assets yet but it's good to have them. I will add event emitting into the DiamondStorageLib itself.

2023-11-21 16:23 UTC, kavsky02 commented on contracts/facets/GmxV2Facet.sol
> +        }
Okay! We don't have events for removing/adding owned assets yet but it's good to have them. I will add event emitting into the DiamondStorageLib itself.

2023-11-21 16:24 UTC, kavsky02 commented on contracts/facets/GmxV2Facet.sol
> +        DiamondStorageLib.unfreezeAccount(msg.sender);
There already is an event being emitted inside of the DiamondStorageLib

2023-11-21 16:24 UTC, kavsky02 commented on contracts/facets/GmxV2Facet.sol
> +    function _deposit(address gmToken, address depositedToken, uint256 tokenAmount, uint256 minGmAmount, uint256 executionFee) internal nonReentrant noBorrowInTheSameBlock onlyOwner {
Ok!

2023-11-21 16:24 UTC, kavsky02 commented on contracts/facets/GmxV2Facet.sol
> +    function _withdraw(address gmToken, uint256 gmAmount, uint256 minLongTokenAmount, uint256 minShortTokenAmount, uint256 executionFee) internal nonReentrant noBorrowInTheSameBlock onlyOwnerNoStaySo
Ok!

2023-12-08 11:17 UTC, kavsky02 commented on contracts/facets/GmxV2Facet.sol
> +    function getGMX_V2_ROUTER() internal pure virtual returns (address);
Done

2023-12-08 11:17 UTC, merged