WIP - first working version of YieldYak staking
DeltaPrimeLabs/deltaprime-primeloans pull request #57
Opened 2022-04-01 17:06 UTC by kavsky02

2022-04-05 18:59 UTC, c-gma commented on contracts/SmartLoan.sol
> +    getYakAvaxStakingContract().approve(address(yakRouter), getYakAvaxStakingContract().balanceOf(address(this)));
It's always more secure to approve as little as possible in this case targetAvaxAmount

2022-04-05 19:25 UTC, c-gma requested changes

2022-04-05 19:25 UTC, c-gma commented on contracts/SmartLoan.sol
> +    yakRouter.unstakeAVAXForASpecifiedAmount(targetAvaxAmount);
Calling an external function we should alway assume that it may fail (revert). In this case it could be caused by payable(msg.sender).safeTransferETH(address(this).balance); [not likely], but yak may always update the logic. To be on the safe side we should try to catch any error using the call pattern and continue gracefully not blocking the liquidation

2022-04-05 19:25 UTC, c-gma commented on contracts/SmartLoan.sol
> +    getYakAvaxStakingContract().approve(address(yakRouter), amount);
safeApprove please

2022-04-05 19:25 UTC, c-gma commented on contracts/SmartLoan.sol
> +    bool success = yakRouter.unstakeAVAX(amount);
Let's keep that in a single line, it's a common pattern:
require(yakRouter.unstakeAVAX(amount), "Unstaking failed");

2022-04-05 19:25 UTC, c-gma commented on contracts/SmartLoan.sol
> +    total += getYieldYakRouter().getTotalStakedValue();
For the simplicity lets keep it here, but let's please also discuss how to best treat staking. 
Currently, we don't take into account the possession of the staked token (https://snowtrace.io/token/0x957ca4a4aa7cdc866cf430bb140753f04e273bc0)
and we may treat is as an additional asset in our wallet.

2022-04-05 19:25 UTC, c-gma commented on contracts/interfaces/IYakStakingAVAXAAVEV1.sol
> +// SPDX-License-Identifier: UNLICENSED
Would it be possible to reference the contracts by importing node modules?

2022-04-05 19:25 UTC, c-gma commented on test/integration/yield-yak-router.test.ts
> +describe('Yield Yak test', () => {
Have we got any tests for staking from the SmartLoan?

2022-04-06 18:13 UTC, kavsky02 commented on contracts/SmartLoan.sol
> +    yakRouter.unstakeAVAXForASpecifiedAmount(targetAvaxAmount);
Good point. I added the call pattern usage and as of now we don't do anyhthing with the result really as selloutStakedAVAX() is only used inside of the liquiditation but at least this will not block the liquidation anymore and in future we may choose to use the operation result in a different way.

2022-04-06 18:16 UTC, kavsky02 commented on contracts/SmartLoan.sol
> +    total += getYieldYakRouter().getTotalStakedValue();
Is it possible for RedStone to provide us with a price of the YRT receipt token?

2022-04-06 18:17 UTC, kavsky02 commented on test/integration/yield-yak-router.test.ts
> +describe('Yield Yak test', () => {
Yes, they can be found in the `smart-loan.test.ts` under the sections: `A loan with staking operations` & `A loan with staking liquidation`

2022-04-06 18:23 UTC, kavsky02 commented on contracts/interfaces/IYakStakingAVAXAAVEV1.sol
> +// SPDX-License-Identifier: UNLICENSED
We would need access to the https://github.com/yieldyak/smart-contracts/blob/master/contracts/strategies/AaveStrategyAvaxV1.sol file but I couldn't find yak npm repository. I know that for example in Remix IDE it's possible to directly import github-stored contracts but I don't think it's a possibility in a local development. Is there another way (apart from copying it to our repo) to access this contract if it's only available in yak's github?

2022-04-07 08:21 UTC, c-gma commented on contracts/SmartLoan.sol
> +    total += getYieldYakRouter().getTotalStakedValue();
That should be possible, we'll just need to check what kind of logic is involved into calculation of that.

2022-04-07 08:23 UTC, c-gma commented on contracts/interfaces/IYakStakingAVAXAAVEV1.sol
> +// SPDX-License-Identifier: UNLICENSED
You could directly reference github repo instead of npm:
https://www.pluralsight.com/guides/install-npm-packages-from-gitgithub

2022-04-07 08:27 UTC, c-gma commented
Changes look good there is still one issue before the merge:
You updated approve -> safeApprove in the sellout method (actually there we want a normal approve not to block the liquidiation, so please revert)
I've suggested adding safeApprove to the public unstake function, where we could communicate the error to user.

2022-04-08 10:19 UTC, kavsky02 commented on contracts/interfaces/IYakStakingAVAXAAVEV1.sol
> +// SPDX-License-Identifier: UNLICENSED
Awesome, this works. Thanks :)

2022-04-08 10:32 UTC, kavsky02 commented on contracts/interfaces/IYakStakingAVAXAAVEV1.sol
> +// SPDX-License-Identifier: UNLICENSED
![image](https://user-images.githubusercontent.com/95619352/162418417-28aa97ac-9eea-4890-9627-7e30af20c6af.png)
Actually it turns out that using their repository to obtain this single contract introduces a lot of mess, because firstly - hardhat won't compile the contracts because of the invalid `package.json` in their repository, and secondly there is a breaking-change solidity versions mismatch `0.7.3` vs `0.8.4` between the contracts. To fix this it would require manual changes that everyone would have to always remember to add locally and at this point I just don't think it's worth the additional hassle in comparision to having one additional partial interface in our repo (the contract itself doesn't have a specific interface defined so we can't just copy the interface file).

2022-04-08 11:44 UTC, merged