Erc20 denominated pool
DeltaPrimeLabs/deltaprime-primeloans pull request #75
Opened 2022-04-25 18:37 UTC by mbare0

2022-05-03 12:25 UTC, kavsky02 requested changes
Initial review of the most important contracts.
I'll go throught the factory & mock contracts & tests later and provide you with additional feedback

2022-05-03 12:25 UTC, kavsky02 commented on contracts/SmartLoan.sol
> +    uint256 poolTokenPrice = repayConfig.prices[repayConfig.poolAssetIndex];
It seems like this variable in no longer used?

2022-05-03 12:25 UTC, kavsky02 commented on contracts/SmartLoan.sol
> +  function repayUsdAmount(RepayConfig memory repayConfig) private returns (uint256) {
Function name is `repayUsdAmount` but it seems that there is no to/from usd conversion? The `poolTokenPrice ` variable in not being used and the `leftToRepay` as well as `neededTokensForRepay` are based ond tokens borrowed - not their usd valuation.

2022-05-03 12:25 UTC, kavsky02 commented on contracts/SmartLoan.sol
> +          leftToRepayInUsd * 10 ** poolToken.decimals() / (prices[assetIndex]) / 10**10,
OKay so now I see that here in this context the `repayUsdAmount()` function is being used to repay a specific usd-value of tokens indeed but the function (`repayUsdAmount()`) itself is usd-valuation agnostic really.

Maybe we can change it's name to better describe what it actually does?

2022-05-03 12:25 UTC, kavsky02 commented on contracts/SmartLoan.sol
> +    WAVAX(payable(getExchange().getAssetAddress(assets[0]))).deposit{value: msg.value}();
Possibly we could save gas on this call here as well (see: other WAVAX-related comments)

2022-05-03 12:25 UTC, kavsky02 commented on contracts/SmartLoan.sol
> +  function liquidateLoan(uint256 toRepayInUsd, uint256[] memory orderOfPools) external payable nonReentrant {
This function is quite humongous, maybe we can split it into a smaller more narrow-scope functions?
Even simple extraction of the parts that repay assets without swapping and then with swapping into a separate methods should help a lot for readibility.

2022-05-03 12:25 UTC, kavsky02 commented on contracts/SmartLoan.sol
> +    WAVAX wavaxToken = WAVAX(payable(getExchange().getAssetAddress(getExchange().getAllAssets()[0])));
Possibly we could save gas on this call here as well (see: other WAVAX-related comments)

2022-05-03 12:25 UTC, kavsky02 commented on contracts/SmartLoan.sol
> +   * Returns the current value of a loan in USD including cash and investments
`cash` -> `native currency`?

2022-05-03 12:25 UTC, kavsky02 commented on contracts/SmartLoan.sol
> +   * Returns the current value of a loan in USD including cash and investments
`cash` -> `native currency`?

2022-05-03 12:25 UTC, kavsky02 commented on contracts/SmartLoan.sol
> +    uint256 total = 0;
Shouldn't we start with `address(this).balance`? As to take into account AVAX (not only WAVAX)?

2022-05-03 12:25 UTC, kavsky02 commented on contracts/SmartLoan.sol
> +   * is being sold.
Move to a line above

2022-05-03 12:25 UTC, kavsky02 commented on contracts/SmartLoan.sol
> +  function sellAssetsForTargetAmount(bytes32 soldAsset, bytes32 boughtAsset, uint256 targetAmount) private {
Maybe we can change it to `swapAssetsForTargetAmount`?

2022-05-03 12:25 UTC, kavsky02 commented on contracts/SmartLoan.sol
> +   * If there is not enough AVAX balance to repay the _repayAmount then the available AVAX balance will be repaid.
Is this function AVAX-only?

2022-05-03 12:25 UTC, kavsky02 commented on contracts/SmartLoan.sol
> +    //TODO: return from unstakeAVAX the real value ustaken
What do you mean by "real"?

2022-05-03 13:37 UTC, kavsky02 commented on contracts/interfaces/IAssetsExchange.sol
> +   * @dev _minAmountOut minimum amount of the AVAX token to be bought
`AVAX` -> `boughToken`?

2022-05-03 13:41 UTC, kavsky02 commented on contracts/upgraded/SmartLoansFactoryWithAccessNFT.sol
> +    function createAndFundLoan(bytes32 fundedAsset, uint256 _amount, uint256 _initialDebt) public override oneLoanPerOwner hasAccessNFT returns (SmartLoan) {
Can't we simply use `super.createAndFundLoan()`?

2022-05-03 13:42 UTC, kavsky02 commented on hardhat.config.ts
> +        version: "0.4.22",
What do we need this version for?

2022-05-03 13:43 UTC, kavsky02 commented on hardhat.config.ts
> +      allowUnlimitedContractSize: true,
Do the contracts meet the SC max limit size regardless?

2022-05-03 13:44 UTC, kavsky02 commented on hardhat.config.ts
> +import "hardhat-contract-sizer";
If we want to include `hardhat-contract-sizer` into our repo then maybe we should at least add its config with the `auto-run-on-compile` disabled so it doesn't affect compilation/tests runtime?

2022-05-04 14:02 UTC, mbare0 commented on contracts/ERC20Pool.sol
> +  function _transferToPool(address payer, uint256 amount) internal virtual {
yes, I like it

2022-05-04 14:04 UTC, mbare0 commented on contracts/PangolinExchange.sol
> +    require(soldTokenAddress != address(0), "Unsupported asset");
right

2022-05-04 14:06 UTC, mbare0 commented on contracts/PangolinExchange.sol
> +   * @dev _exactAmountIn exact amount of the ERC20 token to be sold
updated

2022-05-04 14:06 UTC, mbare0 commented on contracts/PangolinExchange.sol
> +   * @dev _minAvaxAmountOut minimum amount of the ERC20 token to be bought
updated

2022-05-04 14:07 UTC, mbare0 commented on contracts/PangolinExchange.sol
> +   * Returns a path containing tokens' addresses and chosen
removed

2022-05-04 14:08 UTC, mbare0 commented on contracts/PangolinExchange.sol
> +   * @param boughtToken the name of sold token
corrected

2022-05-04 14:11 UTC, mbare0 commented on hardhat.config.ts
> +        version: "0.4.22",
for WAVAX.sol file

2022-05-04 14:11 UTC, mbare0 commented on hardhat.config.ts
> +      allowUnlimitedContractSize: true,
no

2022-05-04 14:13 UTC, mbare0 commented on contracts/interfaces/IAssetsExchange.sol
> +   * @dev _minAmountOut minimum amount of the AVAX token to be bought
right

2022-05-04 14:14 UTC, mbare0 commented on contracts/SmartLoan.sol
> +   * If there is not enough AVAX balance to repay the _repayAmount then the available AVAX balance will be repaid.
this method is outdated, removing

2022-05-04 14:14 UTC, mbare0 commented on contracts/SmartLoan.sol
> +  function sellAssetsForTargetAmount(bytes32 soldAsset, bytes32 boughtAsset, uint256 targetAmount) private {
yes, I like it

2022-05-04 14:15 UTC, mbare0 commented on contracts/SmartLoan.sol
> +   * is being sold.
outdated method, removing

2022-05-04 14:15 UTC, mbare0 commented on contracts/SmartLoan.sol
> +    uint256 total = 0;
very good point

2022-05-04 14:21 UTC, mbare0 commented on contracts/SmartLoan.sol
> +    token.transfer(msg.sender, _amount);
👍

2022-05-04 14:25 UTC, mbare0 commented on contracts/SmartLoan.sol
> +    TransferHelper.safeTransfer(address(soldToken), address(getExchange()), _maximumSold);
👍

2022-05-04 14:27 UTC, mbare0 commented on contracts/ERC20Pool.sol
> +    TransferHelper.safeTransfer(tokenAddress, receiver, amount);
👍

2022-05-04 14:27 UTC, mbare0 commented on contracts/SmartLoan.sol
> +    TransferHelper.safeTransferFrom(address(token), msg.sender, address(this), _amount);
👍

2022-05-04 14:28 UTC, mbare0 commented on contracts/SmartLoan.sol
> +        TransferHelper.safeTransfer(address(token), msg.sender, balance);
👍

2022-05-04 14:28 UTC, mbare0 commented on contracts/SmartLoan.sol
> +      TransferHelper.safeTransfer(address(token), address(getExchange()), swapped);
👍

2022-05-04 14:29 UTC, mbare0 commented on contracts/SmartLoan.sol
> +    TransferHelper.safeTransfer(address(wrappedNativeToken), msg.sender, Math.min(_bonus, address(this).balance));
👍

2022-05-04 14:30 UTC, mbare0 commented on contracts/SmartLoan.sol
> +      poolToken.transfer(msg.sender, Math.min(availableTokens - repaidAmount, repayConfig.tokensForLiquidator));
👍

2022-05-04 14:34 UTC, mbare0 commented on contracts/PangolinExchange.sol
> +   * @dev soldToken_ sold ERC20 token's address
sounds better to me as well, but what about `soldTokenAddress`? it doesn't sound good when changed to `tokenSoldAddress`

2022-05-04 14:34 UTC, mbare0 commented on contracts/ERC20Pool.sol
> +    TransferHelper.safeTransferFrom(tokenAddress, payer, address(this), amount);
👍

2022-05-04 14:35 UTC, mbare0 commented on contracts/PangolinExchange.sol
> +    TransferHelper.safeTransfer(address(soldToken), msg.sender, soldToken.balanceOf(address(this)));
👍

2022-05-04 14:36 UTC, mbare0 commented on contracts/SmartLoan.sol
> +   * Returns the current value of a loan in USD including cash and investments
what about something like: `Returns the current value of Prime Account in USD including all tokens as well as staking and LP positions`

2022-05-04 14:38 UTC, mbare0 commented on contracts/SmartLoan.sol
> +    WAVAX(payable(getExchange().getAssetAddress(getExchange().getAllAssets()[0]))).deposit{value: msg.value}();
I totally agree with hardcoding wavax address, but not sure about hardcoding calldata (as it affects readability of the contract)

2022-05-04 14:45 UTC, mbare0 commented on contracts/SmartLoan.sol
> +          leftToRepayInUsd * 10 ** poolToken.decimals() / (prices[assetIndex]) / 10**10,
actually you spotted a misnaming, it should be called `repayAmount` because it repays the amount of tokens given as an argument

2022-05-04 14:46 UTC, mbare0 commented on contracts/SmartLoan.sol
> +    WAVAX(payable(getExchange().getAssetAddress(assets[0]))).deposit{value: msg.value}();
👍

2022-05-04 14:46 UTC, mbare0 commented on contracts/SmartLoan.sol
> +    WAVAX wavaxToken = WAVAX(payable(getExchange().getAssetAddress(getExchange().getAllAssets()[0])));
👍

2022-05-04 14:47 UTC, mbare0 commented on contracts/SmartLoan.sol
> +    //TODO: return from unstakeAVAX the real value ustaken
I mean "resulting" -> so the value that is finally provided back to our smart contract

2022-05-04 14:47 UTC, mbare0 commented on contracts/SmartLoan.sol
> +    WAVAX wavaxToken = WAVAX(payable(getExchange().getAssetAddress(getExchange().getAllAssets()[0])));
👍

2022-05-04 14:48 UTC, mbare0 commented on contracts/SmartLoan.sol
> +  function repayUsdAmount(RepayConfig memory repayConfig) private returns (uint256) {
true, it's a wrong naming -> should be `repayAmount`

2022-05-04 15:41 UTC, mbare0 commented on contracts/SmartLoan.sol
> +    address payable nativeAddress = payable(getExchange().getAssetAddress(assets[0]));
👍

2022-05-04 15:48 UTC, mbare0 commented on hardhat.config.ts
> +import "hardhat-contract-sizer";
it's not automatically performed during these tasks, but has to be started with `yarn run hardhat size-contracts`. I will add it to `package.json` so it's clear how to use it

2022-05-04 15:49 UTC, mbare0 commented on hardhat.config.ts
> +      allowUnlimitedContractSize: true,
it's around 33.5KB

2022-05-04 15:50 UTC, mbare0 commented on hardhat.config.ts
> +      allowUnlimitedContractSize: true,
anyway I will comment out this line so it's clear for a developer that the problem persists

2022-05-04 15:51 UTC, mbare0 commented on contracts/upgraded/SmartLoansFactoryWithAccessNFT.sol
> +    function createAndFundLoan(bytes32 fundedAsset, uint256 _amount, uint256 _initialDebt) public override oneLoanPerOwner hasAccessNFT returns (SmartLoan) {
you are right, code is the same

2022-05-04 15:54 UTC, mbare0 commented on contracts/ERC20Pool.sol
> +    require(currentAllowance >= subtractedValue, "Current allowance is smaller than the subtractedValue");
<img width="775" alt="image" src="https://user-images.githubusercontent.com/95619266/166721211-cfde9566-5672-4605-8d49-853eea6e00cc.png">
Last sentence suggests that it should revert

2022-05-05 10:27 UTC, kavsky02 commented on hardhat.config.ts
> +import "hardhat-contract-sizer";
Oh okay, my experience with this library was that it did run automatically on compile but it was probably because I used their example config from https://www.npmjs.com/package/hardhat-contract-sizer and assumed that's the default value for the `runOnCompile` property

2022-05-05 11:43 UTC, jakub-wojciechowski commented on contracts/PangolinExchange.sol
> +    amounts = pangolinRouter.swapExactTokensForTokens(
Should we also somehow handle unsuccessful trades and return the tokens? 
Like: 
(bool success, ) = address(pangolinRouter).call{value: 0}(
      abi.encodeWithSignature("swapExactTokensForAVAX(uint256,uint256,address[],address,uint256)", _exactERC20AmountIn, _minAvaxAmountOut, getPathForTokenToAVAX(tokenAddress), msg.sender, block.timestamp)
    );

2022-05-05 12:08 UTC, jakub-wojciechowski commented on contracts/PangolinExchange.sol
> +  event TokenSwap(address indexed seller, bytes32 soldToken, bytes32 boughtToken, uint256 amountSold, uint256 amountBought, uint256 timestamp);
Do we somehow use this event in our front-end. 
It's possible to trigger this event outside of our smart-loan context, so someone could corrupt this data.

2022-05-05 12:11 UTC, jakub-wojciechowski commented on contracts/SmartLoanProperties.sol
> +  function getPoolsAssetsIndices() public virtual view returns (uint8[1] memory) {
Shouldn't that also be parametrized by a pool asset name?

2022-05-05 12:13 UTC, jakub-wojciechowski commented on contracts/WrappedPool.sol
> +contract WrappedPool is ERC20Pool {
Should we call it WrappedAVAX pool, as we use WAVAX below as the only wrapped token?

2022-05-17 16:54 UTC, mbare0 commented on contracts/WrappedPool.sol
> +contract WrappedPool is ERC20Pool {
👍

2022-05-17 16:55 UTC, mbare0 commented on contracts/PangolinExchange.sol
> +  event TokenSwap(address indexed seller, bytes32 soldToken, bytes32 boughtToken, uint256 amountSold, uint256 amountBought, uint256 timestamp);
frontend will use `Swap` event from `SmartLoan`

2022-05-17 16:57 UTC, mbare0 commented on contracts/SmartLoanProperties.sol
> +  function getPoolsAssetsIndices() public virtual view returns (uint8[1] memory) {
after working with new liquidation mechanism (without swaps in SmartLoan) I see that this parametrization with pool indices can  be confusing. It was done like that to optimize iterating over pools, but maybe it would be better to parametrize bytes32 token symbols to make it more clear

2022-05-30 11:50 UTC, mbare0 commented on contracts/PangolinExchange.sol
> +    amounts = pangolinRouter.swapExactTokensForTokens(
In SmartLoan we will perform `approve` and `swap` in one transaction, so it shouldn't make difference (because a transaction would fail anyway). But to be safer it's better to do the way you described.
Only issue I see is that it will be somehow more difficult to extract Pangolin revert messages once transaction fails

2022-08-17 11:22 UTC, closed without merging